FROM ubuntu:18.04

COPY package.json /src/package.json
COPY package-lock.json /src/package-lock.json

ENV MONGO_URL=mongodb://mongodb:27017/tdarr
ENV PORT=8265
ENV ROOT_URL=http://0.0.0.0/
ENV NODE_ARGS="--max-old-space-size=4096"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y git-core subversion build-essential gcc-multilib sudo
RUN apt-get install dbus-x11 packagekit-gtk3-module libcanberra-gtk-module -y
RUN apt-get install dbus libnotify4 libnss3 libxss1 xdg-utils trash-cli  trash-cli libglib2.0-bin gvfs-bin -y
RUN apt install curl
RUN curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
RUN apt install nodejs
RUN apt-get install -y software-properties-common && apt-get update
RUN add-apt-repository ppa:jonathonf/ffmpeg-4 && apt-get update && apt-get -y install ubuntu-restricted-extras
RUN sudo add-apt-repository ppa:stebbins/handbrake-releases && apt-get update
RUN apt-get -y install handbrake-cli ffmpeg libavcodec-extra libdvdnav4 libdvdread4 libavcodec-extra57 gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly ubuntu-restricted-extras

RUN curl https://install.meteor.com/ | sh

WORKDIR /src

EXPOSE 8265
CMD ["/bin/bash", "-l", "-c", "echo HELLO WORLD && npm ci && npm run start"]
